//
//  BLConstant+Labels.swift
//  RogueKit
//
//  Created by Steve Johnson on 3/2/18.
//

import Foundation
import BearLibTerminal


private let _BLConstant_Map: [Int32: String] = [
  BLConstant.A: "A",
  BLConstant.B: "B",
  BLConstant.C: "C",
  BLConstant.D: "D",
  BLConstant.E: "E",
  BLConstant.F: "F",
  BLConstant.G: "G",
  BLConstant.H: "H",
  BLConstant.I: "I",
  BLConstant.J: "J",
  BLConstant.K: "K",
  BLConstant.L: "L",
  BLConstant.M: "M",
  BLConstant.N: "N",
  BLConstant.O: "O",
  BLConstant.P: "P",
  BLConstant.Q: "Q",
  BLConstant.R: "R",
  BLConstant.S: "S",
  BLConstant.T: "T",
  BLConstant.U: "U",
  BLConstant.V: "V",
  BLConstant.W: "W",
  BLConstant.X: "X",
  BLConstant.Y: "Y",
  BLConstant.Z: "Z",
  BLConstant._1: "1",
  BLConstant._2: "2",
  BLConstant._3: "3",
  BLConstant._4: "4",
  BLConstant._5: "5",
  BLConstant._6: "6",
  BLConstant._7: "7",
  BLConstant._8: "8",
  BLConstant._9: "9",
  BLConstant._0: "0",
//  BLConstant.RETURN: "RETURN",  // duplicate of ENTER
  BLConstant.ENTER: "ENTER",
  BLConstant.ESCAPE: "ESCAPE",
  BLConstant.BACKSPACE: "BACKSPACE",
  BLConstant.TAB: "TAB",
  BLConstant.SPACE: "SPACE",
  BLConstant.MINUS: "MINUS",
  BLConstant.EQUALS: "EQUALS",
  BLConstant.LBRACKET: "LBRACKET",
  BLConstant.RBRACKET: "RBRACKET",
  BLConstant.BACKSLASH: "BACKSLASH",
  BLConstant.SEMICOLON: "SEMICOLON",
  BLConstant.APOSTROPHE: "APOSTROPHE",
  BLConstant.GRAVE: "GRAVE",
  BLConstant.COMMA: "COMMA",
  BLConstant.PERIOD: "PERIOD",
  BLConstant.SLASH: "SLASH",
  BLConstant.F1: "F1",
  BLConstant.F2: "F2",
  BLConstant.F3: "F3",
  BLConstant.F4: "F4",
  BLConstant.F5: "F5",
  BLConstant.F6: "F6",
  BLConstant.F7: "F7",
  BLConstant.F8: "F8",
  BLConstant.F9: "F9",
  BLConstant.F10: "F10",
  BLConstant.F11: "F11",
  BLConstant.F12: "F12",
  BLConstant.PAUSE: "PAUSE",
  BLConstant.INSERT: "INSERT",
  BLConstant.HOME: "HOME",
  BLConstant.PAGEUP: "PAGEUP",
  BLConstant.DELETE: "DELETE",
  BLConstant.END: "END",
  BLConstant.PAGEDOWN: "PAGEDOWN",
  BLConstant.RIGHT: "RIGHT",
  BLConstant.LEFT: "LEFT",
  BLConstant.DOWN: "DOWN",
  BLConstant.UP: "UP",
  BLConstant.KP_DIVIDE: "KP_DIVIDE",
  BLConstant.KP_MULTIPLY: "KP_MULTIPLY",
  BLConstant.KP_MINUS: "KP_MINUS",
  BLConstant.KP_PLUS: "KP_PLUS",
  BLConstant.KP_ENTER: "KP_ENTER",
  BLConstant.KP_1: "KP_1",
  BLConstant.KP_2: "KP_2",
  BLConstant.KP_3: "KP_3",
  BLConstant.KP_4: "KP_4",
  BLConstant.KP_5: "KP_5",
  BLConstant.KP_6: "KP_6",
  BLConstant.KP_7: "KP_7",
  BLConstant.KP_8: "KP_8",
  BLConstant.KP_9: "KP_9",
  BLConstant.KP_0: "KP_0",
  BLConstant.KP_PERIOD: "KP_PERIOD",
  BLConstant.SHIFT: "SHIFT",
  BLConstant.CONTROL: "CONTROL",
  BLConstant.ALT: "ALT",
]

extension BLConstant {
  static func label(for constant: Int32) -> String? {
    return _BLConstant_Map[constant]
  }
}
